function d3ify(figureHandle, saveFileName, d3Params)
% Transliterate a matlab figure into a d3 visualization 
if nargin < 3
    d3Params = parseD3Params([]);
else
    d3Params = parseD3Params(d3Params);
end;
if nargin < 2
    saveFileName = 'd3ifyFigure';
end;
if nargin < 1
    figureHandle = gcf;
end;


axisHandle = get(figureHandle, 'Children');
axisChildren = get(axisHandle, 'Children');
lineSeriesIDXs = strcmp('line', get(get(axisHandle, 'Children'), 'Type'));
lineSeriesHandles = axisChildren(lineSeriesIDXs);


% write x and y data to csv(s)
if numel(lineSeriesHandles) == 0
    disp('no children on this set of axes');
elseif numel(lineSeriesHandles) == 1
    writeCSV(lineSeriesHandles, saveFileName, num2str([]));
else
    for i = 1:numel(lineSeriesHandles)
        writeCSV(lineSeriesHandles(i), saveFileName, i);
    end;
end;


% create a javascript file containing the d3 code
fid = fopen([saveFileName, '.js'], 'w');
% The next chunk of code is responsible for setting up the axes
% d3 figure size
fprintf(fid, ['var margin = ', ...
    '{top: %s, right: %s, bottom: %s, left: %s},\n\t',...
    'width = %s - margin.left - margin.right,\n\t',...
    'height = %s - margin.top - margin.bottom;\n\n'], ...
    num2str(d3Params.margin.top), num2str(d3Params.margin.right), ...
    num2str(d3Params.margin.bottom), num2str(d3Params.margin.left), ...
    num2str(d3Params.width), num2str(d3Params.height));

% x-axis scale
xLims = get(axisHandle, 'xLim');
fprintf(fid, ['var xScale = d3.scale.linear()\n\t', ...
    '.domain([%s, %s])\n\t', ...
    '.range([0, width]);\n\n'], num2str(xLims(1)), num2str(xLims(2)));

% y-axis scale
yLims = get(axisHandle, 'yLim');
fprintf(fid, ['var yScale = d3.scale.linear()\n\t', ...
    '.domain([%s, %s])\n\t', ...
    '.range([height, 0]);\n\n'], num2str(yLims(1)), num2str(yLims(2)));

% x-axis
fprintf(fid, ['var xAxis = d3.svg.axis()\n\t', ...
    '.scale(xScale)\n\t', ...
    '.orient("bottom");\n\n']);

% y-axis
fprintf(fid, ['var yAxis = d3.svg.axis()\n\t', ...
    '.scale(yScale)\n\t', ...
    '.orient("left");\n\n']);

% create line fcn
fprintf(fid, ['var line = d3.svg.line()\n\t', ...
    '.interpolate("linear")\n\t', ...
    '.x(function(d) { return xScale(d.x1); })\n\t', ...
    '.y(function(d) { return yScale(d.y1); });\n\n']);

% create svg 
fprintf(fid, ['var svg = d3.select("body").append("svg")\n\t', ...
    '.attr("width", width + margin.left + margin.right)\n\t', ...
    '.attr("height", height + margin.top + margin.bottom)\n\t', ...
    '.append("g")\n\t', ...
    '.attr("transform", "translate(" + margin.left + ","', ...
    ' + margin.top + ")");\n\n']);

% draw axis and axis labels
% x axis
fprintf(fid, ['svg.append("g")\n', ...
    '.attr("class", "axis")\n', ...
    '.attr("transform", "translate(0, " + height + ")")\n', ...
    '.call(xAxis)']);
% x axis label
if ~isempty(get(get(axisHandle, 'Xlabel'), 'string'))
    fprintf(fid, ...
        ['\n.append("text")\n', ...
        '.attr("x", width/2)\n', ...
        '.attr("y", height/10)\n', ...
        '.style("text-anchor", "middle")\n', ...
        '.text("%s");\n\n'], ...
        get(get(axisHandle, 'Xlabel'), 'string'));
else
    fprintf(fid, ';\n\n');
end;

%y axis 
fprintf(fid, ...
    ['svg.append("g")\n', ...
    '.attr("class", "axis")\n' ...
    '.call(yAxis)']);
% y axis label
if ~isempty(get(get(axisHandle, 'YLabel'), 'string'))
    fprintf(fid, ...
        ['\n.append("text")\n', ...
        '.attr("transform", "rotate(270)")\n', ...
        '.attr("y", -width/12)\n', ...
        '.attr("x", -(height)/2)\n', ...
        '.attr("dy", "1em")\n', ...
        '.style("text-anchor", "middle")\n', ...
        '.text("%s");\n\n'], ...
        get(get(axisHandle, 'Ylabel'), 'string'));
else
    fprintf(fid, ';\n\n');
end;


if numel(lineSeriesHandles) == 0
    disp('no children on this set of axes');
elseif numel(lineSeriesHandles) == 1
    drawLineSeriesObject(fid, lineSeriesHandles, saveFileName, []);
else
    for i = 1:numel(lineSeriesHandles)
        drawLineSeriesObject(fid, lineSeriesHandles(i), saveFileName, i);
    end;
end;

% close the javascript file
fclose(fid);
writeHTML(saveFileName, lineSeriesHandles);



function d3Params = parseD3Params(d3Params)
if isempty(d3Params)
    d3Params = struct('margin',[], 'width', [], 'height', []);
    d3Params.margin = struct('top', [], 'right', [], 'bottom', [], ...
        'left', []);
end;
if ~isfield(d3Params, 'margin');
    d3Params.margin = struct('top', [], 'right', [], 'bottom', [], ...
        'left', []);
end;

if isempty(d3Params.margin.top)
    d3Params.margin.top = 20;
end;

if numel(d3Params.margin.top) > 1 || ~isnumeric(d3Params.margin.top)
    error('d3ify:parseD3Params', ...
        'd3Params.margin.top should be a numeric scalar');
end;


if isempty(d3Params.margin.right)
    d3Params.margin.right = 80;
end;

if numel(d3Params.margin.right) > 1 || ~isnumeric(d3Params.margin.right)
    error('d3ify:parseD3Params', ...
        'd3Params.margin.right should be a numeric scalar');
end;


if isempty(d3Params.margin.bottom)
    d3Params.margin.bottom = 80;
end;

if numel(d3Params.margin.bottom) > 1 || ~isnumeric(d3Params.margin.bottom)
    error('d3ify:parseD3Params', ...
        'd3Params.margin.bottom should be a numeric scalar');
end;


if isempty(d3Params.margin.left)
    d3Params.margin.left = 80;
end;

if numel(d3Params.margin.left) > 1 || ~isnumeric(d3Params.margin.left)
    error('d3ify:parseD3Params', ...
        'd3Params.margin.left should be a numeric scalar');
end;


if isempty(d3Params.width)
    d3Params.width = 960;
end;

if numel(d3Params.width) > 1 || ~isnumeric(d3Params.width)
    error('d3ify:parseD3Params', ...
        'd3Params.width should be a numeric scalar');
end;


if isempty(d3Params.height)
    d3Params.height = 500;
end;

if numel(d3Params.height) > 1 || ~isnumeric(d3Params.height)
    error('d3ify:parseD3Params', ...
        'd3Params.height should be a numeric scalar');
end;

function writeCSV(lineSeriesHandle, saveFileName, i)
% write x and y data to a csv
fid = fopen([saveFileName, 'Data', num2str(i), '.csv'],'w');
fprintf(fid,'%s\r\n','x1,y1');
fclose(fid);
dlmwrite([saveFileName, 'Data', num2str(i), '.csv'], ...
    [get(lineSeriesHandle, 'XData')' get(lineSeriesHandle, 'YData')'], ...
    '-append', 'delimiter',',');

function drawLineSeriesObject(fid, lineSeriesHandle, saveFileName, i)
% load data
fprintf(fid, 'd3.csv("%s", function(mydata)\n{\n', ...
    [saveFileName,'Data', num2str(i), '.csv']);

% plot the data
if strcmp(get(lineSeriesHandle, 'LineStyle'), '-')
    fprintf(fid, ['\tsvg.append("path")\n', ...
        '\t.datum(mydata)\n', ...
        '\t.attr("class", "line%s")\n', ...
        '\t.attr("d", line);\n\n'], num2str(i));
end;

if strcmp(get(lineSeriesHandle, 'Marker'), '.')
    fprintf(fid, ['\tsvg.selectAll("circle%s")\n', ...
        '\t.data(mydata)\n', ...
        '\t.enter()\n', ...
        '\t.append("circle")\n', ...
        '\t.attr("class", "circle%s")\n', ...
        '\t.attr("cx", function(d) {\n\t', ...
        '\treturn xScale(d.x1);\n', ...
        '\t})\n', ...
        '\t.attr("cy", function(d) {\n\t', ...
        '\treturn yScale(d.y1);\n', ...
        '\t})\n', ...
        '\t.attr("r", %s);\n\n'], ...
        num2str(i), num2str(i), ...
        num2str(get(lineSeriesHandle, 'markerSize')/3));
end;

% close the tag from load data
fprintf(fid, '});\n\n');

function writeHTML(saveFileName, lineSeriesHandles)
% Now create a simple html file
fid = fopen('index.html', 'w');
fprintf(fid, ...
    ['<html>\n\t', ...
    '<head>\n\t\t', ...
    '<title> %s </title>\n\t\t', ...
    '<script type="text/javascript" src="d3/d3.v2.js"></script>\n\t\t', ...
    '<style type="text/css">\n\t\t'], saveFileName);

% axes css
fprintf(fid, ...
    ['.axis path,\n\t\t', ...
    '.axis line {\n\t\t\t', ...
    'fill: none;\n\t\t\t', ...
    'stroke: black;\n\t\t\t', ...
    'shape-rendering: crispEdges;\n\t\t', ...
    '}\n\n\t\t', ...
    '.axis text {\n\t\t\t', ...
    'font-family: Helvetica, Arial, sans-serif;\n\t\t\t', ...
    'font-size: 16px;\n\t\t', ...
    '}\n\n\t\t']);

% Put lineseriesobject css here
if numel(lineSeriesHandles) == 0
    disp('no children on this set of axes');
elseif numel(lineSeriesHandles) == 1
    if strcmp(get(lineSeriesHandles, 'LineStyle'), '-')
        writeLineCSS(fid, lineSeriesHandles, [])
    elseif strcmp(get(lineSeriesHandles, 'Marker'), '.')
        writePointsCSS(fid, lineSeriesHandles, []);
    end;
else
    for i = 1:numel(lineSeriesHandles)
        if strcmp(get(lineSeriesHandles(i), 'LineStyle'), '-')
            writeLineCSS(fid, lineSeriesHandles(i), i)
        elseif strcmp(get(lineSeriesHandles(i), 'Marker'), '.')
            writePointsCSS(fid, lineSeriesHandles(i), i);
        end;
    end;
end;

% close css tags and call the javascript    
fprintf(fid, ...
    ['</style>\n\t', ...
    '</head>\n\t', ...
    '<body>\n\t\t', ...
    '<div class="content">\n\t\t', ...
    '<script type="text/javascript" src="%s.js"></script>\n\t\t', ...
    '</div>\n\t', ...
    '</body>\n', ...
    '</html>', ...
    ], saveFileName);
fclose(fid);

function writePointsCSS(fid, lineSeriesHandle, i)
circleFill = ['#', ...
    reshape(dec2hex(round(255 * get(lineSeriesHandle, 'Color')))', 1, 6)];
circleStroke = ['#', ...
    reshape(dec2hex(round(255 * get(lineSeriesHandle, 'Color')))', 1, 6)];
fprintf(fid, ...
    ['.circle%s {\n\t\t\t', ...
    'fill: %s;\n\t\t\t', ...
    'stroke: %s;\n\t\t', ...
    '}\n\n\t\t'], num2str(i), circleFill, circleStroke);

function writeLineCSS(fid, lineSeriesHandle, i)
lineStroke = ['#', ...
    reshape(dec2hex(round(255 * get(lineSeriesHandle, 'Color')))', 1, 6)];
lineStrokeWidth = [num2str(get(lineSeriesHandle, 'LineWidth')), ' px'];
fprintf(fid, ...
    ['.line%s {\n\t\t\t', ...
    'fill: none;\n\t\t\t', ...
    'stroke: %s;\n\t\t\t', ...
    'stroke-width: %s;\n\t\t', ...
    '}\n\t\t'], ...
    num2str(i), lineStroke, lineStrokeWidth);



% Created by Matt Best on 3/16/13

