function d3ify(figureHandle, saveFileName, d3Params)
% Transliterate a matlab figure into a d3 visualization
%
% d3ify(figureHandle) generates the scaffolding for a d3.js visualization
% specified by the figure handle, figureHandle
%
% d3ify(figureHandle, saveFileName) saves the output files with the string
% saveFileName
%
% d3ify(figureHandle, saveFileName, d3Params) d3Params is a structure with
% fields:
%   margin (with subfields)
%     top
%     bottom
%     left
%     right
%
%   width -- output size in pixels
%
%   height -- output size in pixels
%
%   plotType {('cart'), 'polar'}
%
% Example 1
%   x = 0:.01:2*pi;
%   y = sin(x) + .25*randn(size(x));
% 
%   figure;
%   plot(x, y, '.', 'markerSize', 8, 'color', [.25 .25 .75]);
%   d3ify(gcf, 'mat2d3Test');
% 
% Example 2
%   y = [sin(x); sin(x + pi/16); sin(x + pi/8); ...
%       sin(x + 3*pi/16); sin(x + pi/4)];
%   figure;
%   set(gca, 'nextPlot', 'replaceChildren');
%   set(gca, 'colorOrder', jet(5))
%   plot(x, y, 'lineWidth', 2)
%   d3ify(gcf, 'mat2d3Test')



if nargin < 3
    d3Params = parseD3Params([]);
else
    d3Params = parseD3Params(d3Params);
end;
if nargin < 2
    saveFileName = 'd3ifyFigure';
end;
if nargin < 1
    figureHandle = gcf;
end;

axisHandle = get(figureHandle, 'Children');
axisChildren = get(axisHandle, 'Children');
lineSeriesIDXs = strcmp('line', get(get(axisHandle, 'Children'), 'Type'));
lineSeriesHandles = axisChildren(lineSeriesIDXs);

% write x and y data to csv(s)
if numel(lineSeriesHandles) == 0
    disp('no children on this set of axes');
elseif numel(lineSeriesHandles) == 1
    writeCSV(lineSeriesHandles, saveFileName, num2str([]), d3Params);
else
    for i = 1:numel(lineSeriesHandles)
        writeCSV(lineSeriesHandles(i), saveFileName, i, d3Params);
    end;
end;


% create a javascript file containing the d3 code
fid = fopen([saveFileName, '.js'], 'w');


createMargins(fid, d3Params);
createAxes(fid, axisHandle, d3Params);
createLine(fid, d3Params);
createSVG(fid, d3Params);

% draw axis and axis labels
drawAxes(fid, axisHandle, d3Params);


if numel(lineSeriesHandles) == 0
    disp('no children on this set of axes');
elseif numel(lineSeriesHandles) == 1
    drawLineSeriesObject(...
        fid, lineSeriesHandles, saveFileName, [], d3Params);
else
    for i = 1:numel(lineSeriesHandles)
        drawLineSeriesObject(...
            fid, lineSeriesHandles(i), saveFileName, i, d3Params);
    end;
end;


% close the javascript file
fclose(fid);
writeHTML(saveFileName, lineSeriesHandles, d3Params);
% end of main



function d3Params = parseD3Params(d3Params)
if isempty(d3Params)
    d3Params = struct('margin',[], 'width', [], 'height', [], ...
        'plotType', []);

    d3Params.margin = struct('top', [], 'right', [], 'bottom', [], ...
        'left', []);
end;
if ~isfield(d3Params, 'margin');
    d3Params.margin = struct('top', [], 'right', [], 'bottom', [], ...
        'left', []);
end;

if isempty(d3Params.margin.top)
    d3Params.margin.top = 20;
end;

if numel(d3Params.margin.top) > 1 || ~isnumeric(d3Params.margin.top)
    error('d3ify:parseD3Params', ...
        'd3Params.margin.top should be a numeric scalar');
end;


if isempty(d3Params.margin.right)
    d3Params.margin.right = 80;
end;

if numel(d3Params.margin.right) > 1 || ~isnumeric(d3Params.margin.right)
    error('d3ify:parseD3Params', ...
        'd3Params.margin.right should be a numeric scalar');
end;


if isempty(d3Params.margin.bottom)
    d3Params.margin.bottom = 80;
end;

if numel(d3Params.margin.bottom) > 1 || ~isnumeric(d3Params.margin.bottom)
    error('d3ify:parseD3Params', ...
        'd3Params.margin.bottom should be a numeric scalar');
end;


if isempty(d3Params.margin.left)
    d3Params.margin.left = 80;
end;

if numel(d3Params.margin.left) > 1 || ~isnumeric(d3Params.margin.left)
    error('d3ify:parseD3Params', ...
        'd3Params.margin.left should be a numeric scalar');
end;


if ~isfield(d3Params, 'width') || isempty(d3Params.width)
    d3Params.width = 960;
end;

if numel(d3Params.width) > 1 || ~isnumeric(d3Params.width)
    error('d3ify:parseD3Params', ...
        'd3Params.width should be a numeric scalar');
end;


if ~isfield(d3Params, 'height') || isempty(d3Params.height)
    d3Params.height = 500;
end;

if numel(d3Params.height) > 1 || ~isnumeric(d3Params.height)
    error('d3ify:parseD3Params', ...
        'd3Params.height should be a numeric scalar');
end;

if isempty(d3Params.plotType)
    d3Params.plotType = 'cart';
end;

if ~ischar(d3Params.plotType)
    error('d3ify:parseD3Params', ...
        'd3Params.plotType should be a string');
end;

function writeCSV(lineSeriesHandle, saveFileName, i, d3Params)
% write x and y data to a csv
fid = fopen([saveFileName, 'Data', num2str(i), '.csv'],'w');
fprintf(fid,'%s\r\n','x1,y1');
fclose(fid);
if strcmp(d3Params.plotType, 'cart')
    dlmwrite([saveFileName, 'Data', num2str(i), '.csv'], ...
        [get(lineSeriesHandle, 'XData')', ...
        get(lineSeriesHandle, 'YData')'], ...
        '-append', 'delimiter',',');
elseif strcmp(d3Params.plotType, 'polar')
    x = get(lineSeriesHandle, 'XData');
    y = get(lineSeriesHandle, 'YData');
    [t, r] = cart2pol(x, y);
    dlmwrite([saveFileName, 'Data', num2str(i), '.csv'], ...
        [r(:), -t(:) + pi/2], '-append', 'delimiter', ',');
end;

function createMargins(fid, d3Params)
% d3 figure size
if strcmp(d3Params.plotType, 'cart')
    fprintf(fid, ['var margin = ', ...
        '{top: %s, right: %s, bottom: %s, left: %s},\n\t',...
        'width = %s - margin.left - margin.right,\n\t',...
        'height = %s - margin.top - margin.bottom;\n\n'], ...
        num2str(d3Params.margin.top), num2str(d3Params.margin.right), ...
        num2str(d3Params.margin.bottom), num2str(d3Params.margin.left), ...
        num2str(d3Params.width), num2str(d3Params.height));
elseif strcmp(d3Params.plotType, 'polar')
    fprintf(fid, ['var width = %s,\n\t', ...
        'height = %s,\n\t', ...
        'radius = Math.min(width, height) / 2 - %s;\n\n'], ...
        num2str(d3Params.width), num2str(d3Params.height), ...
        num2str(d3Params.margin.top));
end;

function createLine(fid, d3Params)
if strcmp(d3Params.plotType, 'cart');
    fprintf(fid, ['var line = d3.svg.line()\n\t', ...
        '.interpolate("linear")\n\t', ...
        '.x(function(d) { return xScale(d.x1); })\n\t', ...
        '.y(function(d) { return yScale(d.y1); });\n\n']);
elseif strcmp(d3Params.plotType, 'polar')
    fprintf(fid, ['var line = d3.svg.line.radial()\n\t', ...
        '.radius(function(d) { return r(d.x1); })\n\t', ...
        '.angle(function(d) { return (d.y1); });\n\n']);
end;

function createAxes(fid, axisHandle, d3Params)
xLims = get(axisHandle, 'xLim');
if strcmp(d3Params.plotType, 'cart')
    % x-axis scale
    fprintf(fid, ['var xScale = d3.scale.linear()\n\t', ...
        '.domain([%s, %s])\n\t', ...
        '.range([0, width]);\n\n'], num2str(xLims(1)), num2str(xLims(2)));

    % y-axis scale
    yLims = get(axisHandle, 'yLim');
    fprintf(fid, ['var yScale = d3.scale.linear()\n\t', ...
        '.domain([%s, %s])\n\t', ...
        '.range([height, 0]);\n\n'], num2str(yLims(1)), num2str(yLims(2)));

    % x-axis
    fprintf(fid, ['var xAxis = d3.svg.axis()\n\t', ...
        '.scale(xScale)\n\t', ...
        '.orient("bottom");\n\n']);

    % y-axis
    fprintf(fid, ['var yAxis = d3.svg.axis()\n\t', ...
        '.scale(yScale)\n\t', ...
        '.orient("left");\n\n']);
elseif strcmp(d3Params.plotType, 'polar')
    % create scale
    fprintf(fid, ['var r = d3.scale.linear()\n\t', ...
        '.domain([0, %s])\n\t', ...
        '.range([0, radius]);\n\n'], num2str(xLims(2)));
end;

function createSVG(fid, d3Params)
if strcmp(d3Params.plotType, 'cart')
    fprintf(fid, ['var svg = d3.select("body").append("svg")\n\t', ...
        '.attr("width", width + margin.left + margin.right)\n\t', ...
        '.attr("height", height + margin.top + margin.bottom)\n\t', ...
        '.append("g")\n\t', ...
        '.attr("transform", "translate(" + margin.left + ","', ...
        ' + margin.top + ")");\n\n']);
elseif strcmp(d3Params.plotType, 'polar')
    fprintf(fid, ['var svg = d3.select("body").append("svg")\n\t', ...
        '.attr("width", width)\n\t', ...
        '.attr("height", height)\n', ...
        '  .append("g")\n\t', ...
        '.attr("transform", ', ...
        '"translate(" + width / 2 + "," + height / 2 + ")");\n\n']);
end;

function drawAxes(fid, axisHandle, d3Params)
if strcmp(d3Params.plotType, 'cart')
    % x axis
    fprintf(fid, ['svg.append("g")\n', ...
        '.attr("class", "axis")\n', ...
        '.attr("transform", "translate(0, " + height + ")")\n', ...
        '.call(xAxis)']);
    % x axis label
    if ~isempty(get(get(axisHandle, 'Xlabel'), 'string'))
        fprintf(fid, ...
            ['\n.append("text")\n', ...
            '.attr("x", width/2)\n', ...
            '.attr("y", height/10)\n', ...
            '.style("text-anchor", "middle")\n', ...
            '.text("%s");\n\n'], ...
            get(get(axisHandle, 'Xlabel'), 'string'));
    else
        fprintf(fid, ';\n\n');
    end;

    %y axis
    fprintf(fid, ...
        ['svg.append("g")\n', ...
        '.attr("class", "axis")\n' ...
        '.call(yAxis)']);
    % y axis label
    if ~isempty(get(get(axisHandle, 'YLabel'), 'string'))
        fprintf(fid, ...
            ['\n.append("text")\n', ...
            '.attr("transform", "rotate(270)")\n', ...
            '.attr("y", -width/12)\n', ...
            '.attr("x", -(height)/2)\n', ...
            '.attr("dy", "1em")\n', ...
            '.style("text-anchor", "middle")\n', ...
            '.text("%s");\n\n'], ...
            get(get(axisHandle, 'Ylabel'), 'string'));
    else
        fprintf(fid, ';\n\n');
    end;
elseif strcmp(d3Params.plotType, 'polar')
    % draw r axis
    fprintf(fid, ...
        ['var gr = svg.append("g")\n\t', ...
        '.attr("class", "r axis")\n', ...
        '  .selectAll("g")\n\t', ...
        '.data(r.ticks(5).slice(1))\n', ...
        '  .enter().append("g");\n\n']);
    
    fprintf(fid, ...
        ['gr.append("circle")\n\t', ...
        '.attr("r", r)\n\n']);
    
    fprintf(fid, ...
        ['gr.append("text")\n\t', ...
        '.attr("y", function(d) { return -r(d) - 4;})\n\t', ...
        '.attr("transform", "rotate(15)")\n\t', ...
        '.style("text-anchor", "middle")\n\t', ...
        '.text(function(d) { return d; });\n\n']);
    
    % draw a axis
    fprintf(fid, ...
        ['var ga = svg.append("g")\n\t', ...
        '.attr("class", "a axis")\n', ...
        '  .selectAll("g")\n\t', ...
        '.data(d3.range(0, 360, 30))\n', ...
        '  .enter().append("g")\n\t', ...
        '.attr("transform", ', ...
        'function(d) { return "rotate(" + -d + ")"; });\n\n']);
    
    fprintf(fid, ...
        ['ga.append("line")\n\t', ...
        '.attr("x2", radius);\n\n']);
    
    fprintf(fid, ...
        ['ga.append("text")\n\t', ...
        '.attr("x", radius + 6)\n\t', ...
        '.attr("dy", ".35em")\n\t', ...
        '.style("text-anchor", ', ...
        'function(d) { return d < 270 && d > 90 ? "end" : null; })\n\t',...
        '.attr("transform", ', ...
        'function(d) { return d < 270 && d > 90 ? "rotate(180 " + ', ...
        '(radius + 6) + ",0)" : null; })\n\t', ...
        '.text(function(d) { return d + "°" });\n\n']);
end;

function drawLineSeriesObject(...
    fid, lineSeriesHandle, saveFileName, i, d3Params)
% load data
fprintf(fid, 'd3.csv("%s", function(mydata)\n{\n', ...
    [saveFileName,'Data', num2str(i), '.csv']);
% plot the data
if strcmp(d3Params.plotType, 'cart')
    if strcmp(get(lineSeriesHandle, 'LineStyle'), '-')
        fprintf(fid, ['\tsvg.append("path")\n', ...
            '\t.datum(mydata)\n', ...
            '\t.attr("class", "line%s")\n', ...
            '\t.attr("d", line);\n\n'], num2str(i));
    end;
    
    if strcmp(get(lineSeriesHandle, 'Marker'), '.')
        fprintf(fid, ['\tsvg.selectAll("circle%s")\n', ...
            '\t.data(mydata)\n', ...
            '\t.enter()\n', ...
            '\t.append("circle")\n', ...
            '\t.attr("class", "circle%s")\n', ...
            '\t.attr("cx", function(d) {\n\t', ...
            '\treturn xScale(d.x1);\n', ...
            '\t})\n', ...
            '\t.attr("cy", function(d) {\n\t', ...
            '\treturn yScale(d.y1);\n', ...
            '\t})\n', ...
            '\t.attr("r", %s);\n\n'], ...
            num2str(i), num2str(i), ...
            num2str(get(lineSeriesHandle, 'markerSize')/3));
    end;
elseif strcmp(d3Params.plotType, 'polar')
    if strcmp(get(lineSeriesHandle, 'LineStyle'), '-')
        fprintf(fid, ...
            ['svg.append("path")\n\t', ...
            '.datum(mydata)\n\t', ...
            '.attr("class", "line")\n\t', ...
            '.attr("d", line);\n']);
    end;
    
    if strcmp(get(lineSeriesHandle, 'Marker'), '.')
        disp(['This plot option not yet supported; ', ...
            'output may not function properly']);
    end;
end;

% close the tag from load data
fprintf(fid, '});\n\n');

function writeHTML(saveFileName, lineSeriesHandles, d3Params)
% Now create a simple html file
fid = fopen('index.html', 'w');
fprintf(fid, ...
    ['<html>\n\t', ...
    '<head>\n\t\t', ...
    '<title> %s </title>\n\t\t', ...
    '<script type="text/javascript" src="d3/d3.v2.js"></script>\n\t\t', ...
    '<style type="text/css">\n\t\t'], saveFileName);

% axes css
if strcmp(d3Params.plotType, 'cart')
    fprintf(fid, ...
        ['.axis path,\n\t\t', ...
        '.axis line {\n\t\t\t', ...
        'fill: none;\n\t\t\t', ...
        'stroke: black;\n\t\t\t', ...
        'shape-rendering: crispEdges;\n\t\t', ...
        '}\n\n\t\t', ...
        '.axis text {\n\t\t\t', ...
        'font-family: Helvetica, Arial, sans-serif;\n\t\t\t', ...
        'font-size: 16px;\n\t\t', ...
        '}\n\n\t\t']);
elseif strcmp(d3Params.plotType, 'polar')
    fprintf(fid, ...
        ['.frame {\n\t', ...
        'fill: none;\n\t', ...
        'stroke: #000;}\n\n']);
    
    fprintf(fid, ...
        ['.axis text {\n\t', ...
        'font: 10px sans-serif;\n}\n\n']);
    
    fprintf(fid, ...
        ['.axis line {\n\t', ...
        'fill: none;\n\t', ...
        'stroke: #999;\n\t', ...
        'stroke-width: 1;\n\t', ...
        'stroke-dasharray: 1,2;\n}\n\t']);
    
    fprintf(fid, ...
        ['.axis circle {\n\t', ...
        'fill: none;\n\t', ...
        'stroke: #999;\n\t', ...
        'stroke-width: 1;\n\t', ...
        'stroke-dasharray: 1,2;\n}\n\t']);
    
    fprintf(fid, ...
        ['.axis :last-of-type circle  {\n\t', ...
        'stroke: #333;\n\t', ...
        'stroke-dasharray: none;\n\t', ...
        'stroke-width: 1.5;\n}\n\n']);        
end;

% lineseries object css here
if numel(lineSeriesHandles) == 0
    disp('no children on this set of axes');
elseif numel(lineSeriesHandles) == 1
    if strcmp(get(lineSeriesHandles, 'LineStyle'), '-')
        writeLineCSS(fid, lineSeriesHandles, [])
    elseif strcmp(get(lineSeriesHandles, 'Marker'), '.')
        writePointsCSS(fid, lineSeriesHandles, []);
    end;
else
    for i = 1:numel(lineSeriesHandles)
        if strcmp(get(lineSeriesHandles(i), 'LineStyle'), '-')
            writeLineCSS(fid, lineSeriesHandles(i), i)
        elseif strcmp(get(lineSeriesHandles(i), 'Marker'), '.')
            writePointsCSS(fid, lineSeriesHandles(i), i);
        end;
    end;
end;

% close css tags and call the javascript
fprintf(fid, ...
    ['</style>\n\t', ...
    '</head>\n\t', ...
    '<body>\n\t\t', ...
    '<div class="content">\n\t\t', ...
    '<script type="text/javascript" src="%s.js"></script>\n\t\t', ...
    '</div>\n\t', ...
    '</body>\n', ...
    '</html>', ...
    ], saveFileName);
fclose(fid);

function writePointsCSS(fid, lineSeriesHandle, i)
circleFill = ['#', ...
    reshape(dec2hex(round(255 * get(lineSeriesHandle, 'Color')))', 1, 6)];
circleStroke = ['#', ...
    reshape(dec2hex(round(255 * get(lineSeriesHandle, 'Color')))', 1, 6)];
fprintf(fid, ...
    ['.circle%s {\n\t\t\t', ...
    'fill: %s;\n\t\t\t', ...
    'stroke: %s;\n\t\t', ...
    '}\n\n\t\t'], num2str(i), circleFill, circleStroke);

function writeLineCSS(fid, lineSeriesHandle, i)
lineStroke = ['#', ...
    reshape(dec2hex(round(255 * get(lineSeriesHandle, 'Color')))', 1, 6)];
lineStrokeWidth = [num2str(get(lineSeriesHandle, 'LineWidth')), ' px'];
fprintf(fid, ...
    ['.line%s {\n\t\t\t', ...
    'fill: none;\n\t\t\t', ...
    'stroke: %s;\n\t\t\t', ...
    'stroke-width: %s;\n\t\t', ...
    '}\n\t\t'], ...
    num2str(i), lineStroke, lineStrokeWidth);



% Created by Matt Best on 3/16/13

